# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - buildenv
      - run:
          name: download Docker
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
      - save_cache:
          paths:
            - ./venv
            - /tmp/docker
          key: buildenv
      - run:
          name: install Docker
          command: |
            sudo mv -n /tmp/docker/* /usr/bin
      - run:
          name: build image
          command: |
            TAG="auto-$CIRCLE_BUILD_NUM"
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t rcjaustralia/rcj-app-server:$TAG .
            docker push rcjaustralia/rcj-app-server:$TAG
            docker tag rcjaustralia/rcj-app-server:$TAG rcjaustralia/rcj-app-server:latest
            docker push rcjaustralia/rcj-app-server:latest
          